publish_to: none
name: hyper_render_highlight
description: Syntax highlighting plugin for HyperRender using flutter_highlight. Supports 180+ programming languages with multiple themes.
version: 1.1.2
homepage: https://github.com/brewkits/hyper_render
repository: https://github.com/brewkits/hyper_render/tree/main/packages/hyper_render_highlight
issue_tracker: https://github.com/brewkits/hyper_render/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.10.0'

topics:
  - flutter
  - syntax-highlighting
  - code-highlight

dependencies:
  flutter:
    sdk: flutter

  # Publishing: replace path with: hyper_render_core: ^1.1.2
  hyper_render_core:
    path: ../hyper_render_core

  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
