name: hyper_render_html
description: HTML parsing plugin for HyperRender. Converts HTML content to UDT with full CSS support.
version: 1.2.0
homepage: https://github.com/brewkits/hyper_render
repository: https://github.com/brewkits/hyper_render/tree/main/packages/hyper_render_html
issue_tracker: https://github.com/brewkits/hyper_render/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.10.0'

topics:
  - flutter
  - html-renderer
  - html-parser
  - css
  - xss-sanitization

dependencies:
  flutter:
    sdk: flutter

  # Publishing: replace path with: hyper_render_core: ^1.2.0
  hyper_render_core:
    path: ../hyper_render_core

  html: ^0.15.6
  csslib: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
