publish_to: none
name: hyper_render_clipboard
description: Image clipboard support for HyperRender using super_clipboard. Enables copying, saving, and sharing images.
version: 1.1.2
homepage: https://github.com/brewkits/hyper_render
repository: https://github.com/brewkits/hyper_render/tree/main/packages/hyper_render_clipboard

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.10.0"

topics:
  - flutter
  - clipboard
  - image-copy

dependencies:
  flutter:
    sdk: flutter

  hyper_render_core:
    path: ../hyper_render_core

  super_clipboard: ">=0.8.0 <1.0.0"
  http: ^1.2.0
  path_provider: ^2.1.0
  share_plus: ">=11.0.0 <13.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
